### ISSUE TITLE
Mise en place de deux thèmes (noir et blanc)

### ISSUE THREAD

**Issue by EmptySckills** [Virtual-Royaume/Royaume-Website#14]
Il y aura plusieurs themes ? (Blanc/Noir) ?

**Comment by Bluzzi** [comment]
Oui ça sera un de nos objectifs pour ce site, il faudra mettre ça en place. Si tu as des exemples/idées de bonne implémentation de ça avec Tailwind, hésite pas à mettre ça ici.

**Comment by Steellgold** [comment]
Un Toggle de ce style serait nice ? Avec la couleur qui change en disparition/apparition (POV: PowerPoint) 

![image](https://user-images.githubusercontent.com/51505384/208242445-a0c1aff7-a79e-4947-b849-c2622eb6532c.png)

**Comment by Bluzzi** [comment]
Ressource potentiellement utile pour mettre en place un changement de thème optimisé avec Tailwind : https://twitter.com/melvynxdev/status/1615393367030124544
