### ISSUE TITLE
Remplacement de nos icons par la lib Lucide 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Website#16]
[Lucide](https://lucide.dev/docs/lucide-svelte)

**Comment by Steellgold** [comment]
Ne peut pas être réalisé.

Car en environnement de développement cela recharge tous les icônes, qui font que la page met beaucoup de temps à s'afficher et donc non productif pour le développeur

À voir dans le futur si le problème est résolu
