### ISSUE TITLE
Search bar display bug

### ISSUE THREAD

**Issue by Steellgold** [Virtual-Royaume/Royaume-Website#2]
Lorsque que l'on écrit dans la barre de recherche, seulement 10% de l'encadré blanc est écrivable, le fait de ne pas pouvoir accéder à la zone d'écriture (en cliquant sur le rectangle blanc) n'est pas esthétique (d'avoir le I avec la souris) 

![image](https://user-images.githubusercontent.com/51505384/191039706-44eb594a-73c1-4cb0-8ce8-9f2c7f65a98a.png)

**Comment by RomainSav** [comment]
Fixed :)
