### ISSUE TITLE
Migration depuis Storybook vers Histoire

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Website#9]
- migration vers [Histoire](https://histoire.dev/)
- renommer les fichiers `.stories.svelte` en `.story.svelte`

**Comment by Steellgold** [comment]
Composants "Containers"
- Alert ✅ 
- Card ✅

Composants "Form"
- Autocomplete Input ✅
- Checkbox ✅
- Form
  - Aucun fichier Storybook précédemment ajouté
- Image Dropzone ✅
- Input ✅
- Select ✅
- Switch ✅
- Textarea ✅

Composants "Navigation"
- Button ✅
- Loading ✅

Composants "Spécials"
- Aucun fichier Storybook précédemment ajouté

Composants "Texts"
- Text ✅

⚠️ TailwindCSS n'a pas l'air d'être tout à fait fonctionnel avec Histoire, ce qui fait qu'il n'y à aucun style sur n'importe quel composant.
